services:
  - type: web
    name: chartai-backend
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false
      - key: REFERRER_URL
        value: https://chartanalystai.netlify.app
    autoDeploy: true
    plan: free